Make HMR work on windows
hmsk/vite-plugin-elm pull request #287
Opened 2022-07-29 19:09 UTC by andreasewering

On windows there are inconsistencies regarding the file paths because of the different path seperator. This leads to the dependencies variable to be something like this:
```
Compilable Files Map(1) {
  '.../src/Main.elm' => Set(1) {     
    '...\\src\\Translations.elm'
  }
}
```

The Set.has call does not take this inconsistency into account and always fails.
The smallest fix I could find is the application of path.normalize. I'm pretty sure this should not break other operating systems and it fixes the problem on windows.

2022-08-01 03:38 UTC, hmsk requested changes
Thanks for your contribution! maybe you missed to check in changes on imports?

2022-08-01 17:55 UTC, andreasewering commented
You are absolutely right! I did the changes locally and just used github's ui to open the fork so I didn't notice. Thanks.

2022-08-02 02:57 UTC, hmsk approved these changes

2022-08-02 02:57 UTC, merged

2022-08-02 03:02 UTC, hmsk commented
@andreasewering Added you to the contributors list, but I wasn't sure your preferred name/email from git's log so feel free to make a PR to update that.
https://github.com/hmsk/vite-plugin-elm/commit/ee8b65e862a798cfc1d10548a26d78605bde2901

2022-08-04 06:49 UTC, hmsk commented
Released as v2.7.2. It'll be helpful if you check with your actual Windows env 🙏 @andreasewering

2022-08-05 14:51 UTC, andreasewering commented
Works! I just released https://github.com/andreasewering/vite-plugin-travelm-agency and the examples work with HMR on my machine ;)